# Generated by Django 4.0 on 2022-01-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('carburant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=20, null=True)),
                ('prix', models.FloatField()),
                ('stock', models.IntegerField(default=1)),
                ('marque', models.CharField(max_length=50, null=True)),
                ('pays', models.CharField(max_length=50, null=True)),
                ('ref', models.CharField(max_length=50)),
                ('n_chasis', models.CharField(max_length=50, null=True)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
    ]
