# Generated by Django 4.0 on 2022-06-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='sku',
        ),
        migrations.AddField(
            model_name='produit',
            name='Categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
        ),
    ]
